name: NFT Platform Contracts CI

on:
  # We want to trigger the build & test pipelines in every branch.
  push:
    # But do no run the pipeline when only `md` files are modified.
    paths-ignore:
      - '**.md'

jobs:

  check-abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: git --no-pager diff --exit-code artifacts/contracts/RFOXCollection.sol/RFOXCollection.json

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn test
